export const types = Object.freeze({
    FORCAST_START_FETCHING: 'FORCAST_START_FETCHING',
    FORCAST_STOP_FETCHING: 'FORCAST_STOP_FETCHING',
    FORCAST_SET_FETCHING_ERROR: 'FORCAST_SET_FETCHING_ERROR',
    FORCAST_FETCH_ASYNC: 'FORCAST_FETCH_ASYNC',
    FORCAST_FILL: 'FORCAST_FILL',
    IS_SUBMIT_SET: 'IS_SUBMIT_SET',
    IS_CHECKED_SET: 'IS_CHECKED_SET',
    IS_TEMPERATURE_SET: 'IS_TEMPERATURE_SET',
    MAX_TEMPERATURE_SET: 'MAX_TEMPERATURE_SET',
    MIN_TEMPERATURE_SET: 'MIN_TEMPERATURE_SET',
    BUTTON_VALUE_SET: 'BUTTON_VALUE_SET',
    FORCAST_INIT_STATE: 'FORCAST_INIT_STATE',
});
