export const types = Object.freeze({
    FORCAST_START_FETCHING: 'FORCAST_START_FETCHING',
    FORCAST_STOP_FETCHING: 'FORCAST_STOP_FETCHING',
    FORCAST_SET_FETCHING_ERROR: 'FORCAST_SET_FETCHING_ERROR',
    FORCAST_FETCH_ASYNC: 'FORCAST_FETCH_ASYNC',
    FORCAST_FILL: 'FORCAST_FILL',
});
